easy_admin:
  site_name: 'TroskiShop Backoffice'
  entities:
      Product:
        class: TroskiShop\Domain\Model\Product
        label: "No funciona"
        list:
          fields:
            - 'id'
            - {property: 'image', type: 'image', base_path: '%env(UPLOAD_PATH)%'}
            - 'name'
            - 'brand'
            - 'model'
            - 'uri'
            - 'price'
      Order:
        class: TroskiShop\Domain\Model\Order
        list:
          fields: [ 'id', 'createdAt', 'sendingDate', 'deliveryDate', 'deliveredDate' ]
      User:
        class: TroskiShop\Domain\Model\User
        list:
          fields: ['id', 'nif', 'name', 'surname', 'email', 'telephone']
  design:
    form_theme: '@EasyAdmin/crud/form_theme.html.twig'
    menu:
      - {route: 'dashboard', label: 'Dashboard', icon: 'fa fa-home'}
  dashboard:
    controller: TroskiShop\Infrastructure\Framework\Symfony\Controller\Backoffice\BackofficeController
