version: '3.8'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./docker/php/apache/sites-available:/etc/apache2/sites-available
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - symfony
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony

volumes:
  db-data:

networks:
  symfony:
    driver: bridge
